name: Teste Workflow

on: ["push"]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Usar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instalar dependencias
      run: yarn --frozen-lockfile

    - name: Executar testes
      run: yarn test
          

